set -g default-terminal "xterm-256color"

bind-key r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"  
# remap prefix from 'C-b' to 'C-a'
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

bind '%' split-window -h -c '#{pane_current_path}'  # Split panes horizontal
bind '"' split-window -v -c '#{pane_current_path}'  # Split panes vertically


set -g focus-events on

#remap pane navigation to hjkl (be more vi like)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Set tmux to Vi mode
set-window-option -g mode-keys vi

# Scroll up/down with j/k in scroll mode
bind-key -t vi-copy 'j' page-up
bind-key -t vi-copy 'k' page-down

# Copy paste commands in scroll mode
bind-key -t vi-copy 'v' begin-selection                  
bind-key -t vi-copy 'y' copy-selection
